{{- if .Values.cloudflared.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adi-stack.fullname" . }}-cloudflared
  labels:
    {{- include "adi-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudflared
  {{- with (include "adi-stack.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.cloudflared.replicaCount }}
  selector:
    matchLabels:
      {{- include "adi-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cloudflared
  template:
    metadata:
      labels:
        {{- include "adi-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cloudflared
    spec:
      serviceAccountName: {{ include "adi-stack.serviceAccountName" . }}
      {{- include "adi-stack.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if not .Values.openshift.enabled }}
      securityContext:
        {{- toYaml .Values.cloudflared.podSecurityContext | nindent 8 }}
      {{- else }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      {{- end }}
      containers:
        - name: cloudflared
          image: {{ include "adi-stack.cloudflared.image" . }}
          imagePullPolicy: {{ .Values.cloudflared.image.pullPolicy }}
          command:
            - cloudflared
          args:
            - access
            - tcp
            - --hostname
            - {{ .Values.cloudflared.replayHostname }}
            - --listener
            - "0.0.0.0:{{ .Values.cloudflared.listenerPort }}"
          ports:
            - name: tcp-proxy
              containerPort: {{ .Values.cloudflared.listenerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.cloudflared.resources | nindent 12 }}
          {{- if not .Values.openshift.enabled }}
          securityContext:
            {{- toYaml .Values.cloudflared.containerSecurityContext | nindent 12 }}
          {{- else }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
