{{- if and .Values.ingress.enabled (eq (include "adi-stack.ingressType" .) "ingress") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "adi-stack.fullname" . }}
  labels:
    {{- include "adi-stack.labels" . | nindent 4 }}
  {{- with .Values.ingress.kubernetes.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.kubernetes.className }}
  ingressClassName: {{ .Values.ingress.kubernetes.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- else }}
      secretName: {{ include "adi-stack.fullname" . }}-tls
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "adi-stack.fullname" . }}
                port:
                  number: {{ .Values.service.ports.rpc }}
{{- end }}
